language: python
dist: xenial
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pipenv install --dev
script: pipenv run tests
notifications:
  email: false
  slack:
    matrix:
      - sgbcgroup:LQx8YcBhBqAUTON9eMivOuFr
    rooms:
      secure: Fdzf2EpffyQCgWKt5iDCIE7SiX2ElX4wtwcZPCtmlBL58JjxW5yQnh4Wgh7/cOdVs2HNzq6ANyFoVUe5S/2+bW9bjcDuvRLzoVy5FYZNoDQiT2/AphvYeZ1SkGJQsqVtnW+llOSteKRe3lJDipby+mtn8Qphiq96890IItAm6MV1MU08O24WwnB+bUt/GpUY907Q2e9CTL6JRt0GSPO3+azg/WtL9f0AxeJFcqpjJ2sSqXAqwQorB5QNAZJtSnsUO7TTlt1PMaaVa/g2x5xXcioABP37k+9XykidHj32fN1SgdJulbJuJQazpme0blgq8pdxp0ECnSBLba5zuuHzQo1e9pXZV7yil6jCaIhZclBKFDuwx+8zT8Dut7RzJZPd85u0pwHLr1UWdmH1xUQKWjCmQFvAl+tNviYTe0kUKK8OHJCTLHaZ6uAPqA5p0mfT21tTKds0OMfk00fTDxJx7D5HDSbaRtDbgprhld8l5HGNcbdjYmARbYruONw5unV8F+lgpt2FcIoXoPUIK0l8oXXf8Q3kQM1ER2IE3uA2o8a5oTuQQp+tQ8/sbnd4JWy7JbWdywsXmAX/OFpoujfRyMIVx/Y2JoFJ1EXxPwvYmd8Vnt9N/D89hw8Gnz1T3jKSJI9x7iOEYe55Ef0QRR73XfF+aBcvImFPVF20TNbMbi4=

after_success:
  - codecov
deploy:
  provider: pypi
  user: hadrieng
  password:
    secure: ZbJQypOrraPFPuTrovJHDMDOGgpTgV+Am/FDQaWT3O8m9WUnM1V140fegsEv4xRRIlTJHsHNj/zOz5s9CRTjHgB2aA4j73FmuV8CNOBrb54uCC5Msd3m6Y8uHvQwdb85eTQYcTcjmzZNVhTITBFssluvV7C6p6MGsJRjCphjx9reai5xIXS4rR47fcxvchBTdXsu7KUwlMQBueIr+zbILjpjosfeU5/CaY6NPzTQKTe/03IZeC2x5lkI/Sp7LAHZUnHNjtm/sV3b/KduAtuJ2T/TCx+j2O13WH9NcBCBhMRIn3i0567/7hkkJbeUFdeZa4YKkh+hMX1ILrFhlpfIDm04Dod2OrCkISTJ2bZvPCfZGL+vnNJQMZXgvAlirN0hkJ1HfWGq0xIqoooP3J2wGmmWYJCe1lVOSnRzCw/K5/jtKsw+1QcSLpbhTKoMRjhXT8qPPmGwnaLOoR9tv4GXb2wkLxS8Ok/0zgjHu8MAP/0L+qlpLPhFxkfA06IYvTbGsxd0y2ldVFln5Zpkzj48qVuQiJcdKm8ClwI3PWrXLOAs23KltuFgRXthRZOeH6+16AeS/cwrLZ9tHy3thxeYoS6G3eImlaX5D1te/iCKXKNyKOIF2/S4kiQk8Od3C+pKoLsmhsoItWx6wE+Uf0trBjXS3iVs+g+uWGmwaLJiSOk=
  on:
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
