language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script: nosetests
# notifications
notifications:
  slack: sgbcgroup:LQx8YcBhBqAUTON9eMivOuFr
